name: Playwright Tests

on:
  workflow_run:
    workflows: ["Build & Push Playwright Docker Image"]
    types:
      - completed
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - uses: actions/checkout@v4

      - name: Run Playwright tests inside Docker container
        run: |
          docker run --rm \
          ghcr.io/${{ github.repository_owner }}/playwright-tests:latest
          npx playwright test


      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30



          